name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Mint
      uses: fabasoad/setup-mint-action@v1.0.2
      with:
        version: 0.10.0

    - name: Run script
      run: mint test
